spring.datasource.url=jdbc:sqlserver://${SIKALMA_DB_HOST:localhost}:${SIKALMA_DB_PORT:1433};databaseName=${SIKALMA_DB_NAME:sikalma_db};encrypt=true;trustServerCertificate=${SIKALMA_DB_TRUST_CERTIFICATE:true}
spring.datasource.username=${SIKALMA_DB_USER:sikalma_user}
spring.datasource.password=${SIKALMA_DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima
spring.thymeleaf.cache=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/sqlserver/schema.sql
spring.sql.init.continue-on-error=false
spring.security.user.roles=ADMINISTRADOR
